/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/properties` | `/properties`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}${'/(modals)'}/equipments/[id]` | `/equipments/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(authenticated)'}/equipments/[id]` | `/equipments/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(authenticated)'}/properties/[id]` | `/properties/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/properties` | `/properties`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}${'/(modals)'}/equipments/[id]` | `/equipments/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(authenticated)'}/equipments/[id]` | `/equipments/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(authenticated)'}/properties/[id]` | `/properties/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}${'/(tabs)'}/calendar${`?${string}` | `#${string}` | ''}` | `/calendar${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}${'/(tabs)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}${'/(tabs)'}/properties${`?${string}` | `#${string}` | ''}` | `/properties${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/properties` | `/properties`; params?: Router.UnknownInputParams; } | `${'/(authenticated)'}${'/(modals)'}/equipments/${Router.SingleRoutePart<T>}` | `/equipments/${Router.SingleRoutePart<T>}` | `${'/(authenticated)'}/equipments/${Router.SingleRoutePart<T>}` | `/equipments/${Router.SingleRoutePart<T>}` | `${'/(authenticated)'}/properties/${Router.SingleRoutePart<T>}` | `/properties/${Router.SingleRoutePart<T>}` | { pathname: `${'/(authenticated)'}${'/(modals)'}/equipments/[id]` | `/equipments/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(authenticated)'}/equipments/[id]` | `/equipments/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(authenticated)'}/properties/[id]` | `/properties/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
